server:
  port: 9005
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      ## helper库
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ENC(iZSADTmcPfFfXLsAr7HtcYg0om4j/gbuVsIHwUifU9lCjDlTJ3dPHCq+zOOXwIp1kCqGCw+qV+uiAoqESb/MAwPXKdwlTxISV+2+wCmTO96nlMGxjcvPchNh8UW/dfc9BwEg7+pKQlEiwvMPSH7SHbxyvrV2cZwXCWxrhuDkQvJoa2jRnhkcK7p7vO4yaYdGNkb1u9qSvDtGxPITAE5K7Q==)
      username: ENC(gGB2U/HZ3NuRUyx74VRx1w==)
      password: ENC(1oZS23R04+S/FgD/UhJuhB4hfklxKGzJ)
  redis:
    ## 单机配置 ## 没密码不要写 password
    host: localhost
    port: 6379
    timeout: 10000
    ## 哨兵模式
    #    sentinel:
    #      master: mymaster
    #      nodes:
    #        - 192.168.1.200:26379
    #        - 192.168.1.200:26380
    #        - 192.168.1.200:26381
    #      password: s123
    #    password: redis123
    jedis:
      pool:
        max-idle: 8
        max-wait: 10000
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: helper.entity
  typeEnumsPackage: helper.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      logic-delete-value: 1
      logic-not-delete-value: 0
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    ##开启SQL打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 雪花算法
snow-flake:
  machine-identify: 1
swagger:
  path-name: app
  package-name: app
  application-name: 小助手
