server:
  port: 9001
spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    virtual-host: dlx
    username: dlx
    password: dlx
swagger:
  path-name: rabbitmq
  package-name: rabbitmq
  application-name: 测试mq
